### ISSUE TITLE
Incorrect package entry point ?

### ISSUE THREAD

**Issue by bbsimonbb** [la-fabrique/vue-d3-network-graph#13]
I would love this to work. I clone the project, run npm build, get vue-d3-network-graph-0.1.0.tgz, install it into my project like [this](https://stackoverflow.com/a/55560928/1585345). The package looks to be installed (present in my node_modules) but then I have the following error...

```

Failed to resolve entry for package "vue-d3-network-graph". The package may have incorrect main/module/exports specified in its package.json.
17:37:30 [vite] Internal server error: Failed to resolve entry for package "vue-d3-network-graph". The package may have incorrect main/module/exports specified in its package.json.       
  Plugin: vite:import-analysis
  File: C:/Users/sboddy/source/repos/octopus-devtools/src/App.vue
      at packageEntryFailure (file:///C:/Users/sboddy/source/repos/octopus-devtools/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21822:11)
      at resolvePackageEntry (file:///C:/Users/sboddy/source/repos/octopus-devtools/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21819:5)
      at tryNodeResolve (file:///C:/Users/sboddy/source/repos/octopus-devtools/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21557:20)
      at Context.resolveId (file:///C:/Users/sboddy/source/repos/octopus-devtools/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21321:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.resolveId (file:///C:/Users/sboddy/source/repos/octopus-devtools/node_modules/vite/dist/node/chunks/dep-0bae2027.js:41407:32)
      at async TransformContext.resolve (file:///C:/Users/sboddy/source/repos/octopus-devtools/node_modules/vite/dist/node/chunks/dep-0bae2027.js:41154:23)
      at async normalizeUrl (file:///C:/Users/sboddy/source/repos/octopus-devtools/node_modules/vite/dist/node/chunks/dep-0bae2027.js:39506:34)
      at async TransformContext.transform (file:///C:/Users/sboddy/source/repos/octopus-devtools/node_modules/vite/dist/node/chunks/dep-0bae2027.js:39647:47)
      at async Object.transform (file:///C:/Users/sboddy/source/repos/octopus-devtools/node_modules/vite/dist/node/chunks/dep-0bae2027.js:41480:30)
```

**Comment by deka** [comment]
HI @bbsimonbb,
This library is not production ready, but i update dependencies, update build process and add package configurations.
Can you try the [PR Branch](https://github.com/la-fabrique/vue-d3-network-graph/tree/13-incorrect-package-entry-point) ? 
Regards
